version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test